### ISSUE TITLE
[SA] Crash due to "No burn on flipped" function

### ISSUE THREAD

**Issue by Shamphin** [user-grinch/Cheat-Menu#105]
In the "Vehicle" tab, if you turn on "No burn on flipped" and flip the car, and then exit that flipped car, the game will crash.

**Comment by Cuprudnum** [comment]
@user-grinch I downloaded the new beta version of the cheat menu from Discord and this bug is still present. Also, there is a new bug. When I just start the game, and immediately turn on this feature, the game immediately crashes. You have to wait a while to be able to turn it on without crashing the game.
