### ISSUE TITLE
Option to disable online features

### ISSUE THREAD

**Issue by someshittyeletronicmusicband** [user-grinch/Cheat-Menu#66]
I really don't want mods doing stuff other than what they are supposed to do, including connecting to the internet to check for updates without my permission. Can you please at least add an option to toggle it off?

**Comment by user-grinch** [comment]
Personally, I'm biased against that. I prefer people to update to the latest version as they come out. I've seen people still using v1.7 or even older (which you shouldn't do since those codes are really buggy ). At one point I even considered hard locking older versions when the new ones come out but scrapped the idea. I do get that update notification can be annoying at times but that's the only way to make people update ( lol ).

As for privacy concerns, I don't think there's anything to worry about. The menu is 100% open source. Anyone can check the code and (if they don't trust my builds) just build one themselves.

I'll keep this issue open. If enough people want this, I might reconsider.

**Comment by floppyD** [comment]
I agree that it should be optional, at least there should be an option to opt-out. Just imagine if every mod could connect to the internet and check for updates without your consent, wouldn't be pretty.
